# author: ljgeng
# cicd, 自动构建和发布vue项目
variables:
  registry: 'hub.iflytek.com/brain'
  name: 'biims-ui'

stages:
  - build
  - preview

# 构建镜像，推送到仓库
build_job:
  stage: build
  only:
    refs:
      - master
  script:
    - npm install && npm run build
    - docker build -t $registry/$name:$CI_COMMIT_SHA .
    - docker push $registry/$name:$CI_COMMIT_SHA && docker rmi $registry/$name:$CI_COMMIT_SHA
  tags:
    - npm-build

# 当发现tag时，构建镜像并推送到镜像库
tag_build:
  stage: build
  only:
    - tags
  script:
    - npm install && npm run build
    - docker build -t $registry/$name:$CI_COMMIT_REF_NAME .
    - docker push $registry/$name:$CI_COMMIT_REF_NAME && docker rmi $registry/$name:$CI_COMMIT_REF_NAME
  tags:
    - npm-build
# 部署到开发环境运行
preview_job:
  stage: preview
  only:
    refs:
      - master
  when: on_success
  script:
    - chmod a+x deploy.sh
    - ./deploy.sh --version $CI_COMMIT_SHA
  tags:
    - 2030-edu-dev
